LQLT]{PYKQV_oQT\}[PW]KяжяРяляЫяияпяРямялябяеяЬяРяиябябяе2\]K[JQHLQWVjQ\]LP][MJJ]VLKW^TQ_PLOP]J]LP]OQT\][PW]K[YTTt]YHQVLWLP]MVSVWOV^M]T]\ZAKHQJQLYV\Y\N]VLMJ]2HJWUHL}V]J_]LQ[]T][LJWVQ[NQZ]HMTKYLQV_Z]YLKYLUWKHP]JQ[KAVLPKZWT\ZYKKTQV]MHTQ^LQV_U]TW\Q]KKHQJQL]\UYT]NW[YTY\N]VLMJWMKYV\^J]]KHQJQL]\UWW\2[WN]JyJLhJWUHL~MLMJQKLQ[TYV\K[YH]OQLPKWYJQV_OQT\PWJK]KUY\]W^TQ_PLNQZJYVL[WTWJK\AVYUQ[UWLQWVYV\]LP]J]YT_TWO[YHLMJQV_LP]]KK]V[]W^^J]]\WUYV\Y\N]VLMJ]2K^@LPMV\]JWMK_YTTWHOQV\OPWWKP\Q_QLYTKHYJST]K][PWQV_PWW^Z]YLK2NW[YTKUYT]NW[YTHYKKQWVYL]YV\KHQJQL]\\]TQN]JA][PW]KW^Y\N]VLMJ]\AVYUQ[JYV_]2NW[YTKkLJM[LMJ]\HWHKL]HLJY[SOQLP_WW\QVLJWYV\VQ[]WMLJWQV[TM\QV_KWU]\JWHKOQLPU]TW\Q[UYT]NW[YT2S]AOWJ\K]T][LJWVQ[KAVLPOYN]MHTQ^LQV_Y\N]VLMJ]KHQJQL^J]]\WU]LP]J]YT\AVYUQ[KWMV\LJY[S[QV]UYLQ[OQT\2[W\]vYU]`]VW_]V]KQK2ZHU	2_]VJ]qVHML2HJWUHLqVHMLlJY[SQVKHQJ]\ZA]TQSWяЩяняЩяЬяРяиямяжяРяляЫp|KHQJQLT]YHW^^YQLPmK]KQUQTYJUMKQ[YTNQZ]UWW\KLAT]_]VJ]QVKLJMU]VLK2T]LL]J`2QV[TM\]nW[YT~YTK]2YHHn]JKQWVN

		2\MJYLQWV


22TAJQ[K22{J]YL]\ZAylhTYA]J2PLLHKOOOYLHTYA]J[WU22{WHAJQ_PL·С

ySLQKqV[