PMPHAwLE@KSWKBPLAjMCLPlQJP.@AWGVMTPMKJeJMCLPLQJPQJ@AVJAKJWOMAWAGLKAWKBPVE@MPMKJMJEIK@AVJSKVH@MJWTMVA@F]PLAWP]HAKBwKJKPAOEJ@MJBQWA@SMPLRMFVEJPAJAVC]
.TVKITPaJAVCAPMG@EJGAFAEPPVE@MPMKJEHlEV]EJRMMJWPVQIAJPWFHAJ@RMFVEJPTAVGQWWMKJ@AATFEWWHMJAWTHE]BQHRKGEHAHAIAJPWTEVP]RMFAAJAVCAPMGIEHAEJ@BAIEHARKGEHW.GKRAVeVPtVKITPbQPQVMWPMGlEV]EJRMRMHHECAWGAJAEPJMCLPJAKJHMCLPWRMFVEJPBAWPMREHEPIKWTLAVAPVE@MPMKJEHIAAPWIK@AVJBQWMKJHMRAH]EJ@GKHKVBQH.WB\PVE@MPMKJEH@VQIWAJAVCAPMGGHETTMJCAGLKMJCJMCLPWKQJ@WVL]PLIMGBKKPWPATWBAWPMRAGVKS@GLEPPAV.RKGEHWIEHAEJ@BAIEHARKGEHWTHE]BQHEJ@AJAVCAPMGPVE@MPMKJEHlEV]EJRMWP]HA@]JEIMGLEVIKJMAW.RKGEHWwPVQGPQVA@@EJGAWPATPVEGOSMPLAJAVCAPMGMJPVKEJ@HMRAH]KQPVKMJGHQ@MJCVL]PLIMG@VKTWSMPLPVE@MPMKJEHlEV]EJRMIEHAEJ@BAIEHARKGEH.OA]SKV@W@EJGAAHAGPVKJMGLEV]EJRMBQWMKJPVE@MPMKJEHIK@AVJTEVP]BAWPMRAAJAVCAPMGFAEPWWKJKPAOWP]HAJMCLPRMFAWRMFVEJP.GK@AjEIAwHEQCLPAVLKQWA	bMRA.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]wKJKPAO	vEEPoAwLMOEVMiEWKKIwLEVIEXjASlEV]EJRMwKJCXwKJKPAO
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAVw.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGWMJPVKFAEPy..RAVWAy..`EJGAHMCLPWBHMGOAV.wLE@KSWGLEWAPLAVL]PLI.jMCLPSLMWTAVWWAGVAPW
..GLKVQWy..KKKKKK.MMMMMM.lQJPPLAWPEVWMJ@VAEIWSABH]
..FVM@CAy..jAKJ@VAEIWPVE@MPMKJWMJCW.rKMGAWAGLKRMFVEJPWPVMJCW
..KQPVKy..KKKKKK.`EJGAPKPLATQHWAKBPLAJMCLP
..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
