PMPHA`AWAVPhMFAVEPMKJ.@AWGVMTPMKJmJPLAREWPJAWWKBPLA@AWAVPBVAA@KIMWBKQJ@
aGLKAWKBPLATEWPSLMWTAVWKBPLABQPQVAMJEWP]HAVAIMJMWGAJPKBkQPOEWPEJ@aV]OELfE@Q
.TVKITPwKQHBQHLMT	LKTCVKKRAAPLAVAEHW]JPLWWIKKPLFEWWHMJANE^^]GLKV@WHEM@	FEGOVL]PLI@VAEI]EPIKWTLAVAIEHAEJ@BAIEHARKGEHLEVIKJMAWMJPVKWTAGPMRAEJ@HMFAVEPMJCIKK@.GKRAVeVPtVKITPrEWP@AWAVPHEJ@WGETAQJ@AVEWPEVV]WO]APLAVAEHEJ@@VAEIHMOASMPLWLMIIAVMJCWEJ@WGAHAWPMEHHMCLPFAEIWEJ@EI]WPMGEHEQVEIK@AVJEJ@EVPMWPMGWP]HA.WB\CAJPHASMJ@VQWPHA@MWPEJPGLMIAWWKBPWEJ@GVQJGLAGLKMJCSLMWTAVW.RKGEHWIEHAEJ@BAIEHARKGEHWWKBPLEVIKJMAWWKQHBQHEJ@MJPVKWTAGPMRA.RKGEHWwPVQGPQVA@LMT	LKTWKQHPVEGOSMPLEWIKKPLMJPVKEJ@VABHAGPMRAKQPVKBAEPQVMJCWKQHBQHIEHAEJ@BAIEHARKGEHLEVIKJMAW.OA]SKV@WLMT	LKTWKQHNE^^JAK	WKQHGLMHHLKTCVKKRAEPIKWTLAVMGVABHAGPMKJ@AWAVPRMFAWHMFAVEPMKJWKQHBQHkQPOEWPaV]OELfE@Q.GK@AjEIA`QJA.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]kQPOEWPgAAhKfMCvQFAaV]OELfE@Q	hMFAVEPMKJ
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAV`.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGWMJPVKSMJ@y.WKBPIEHARKMGAmJPLAWMHAJGAKBWEJ@.WKBPBAIEHARKMGAhMFAVEPMKJEPLEJ@.KKKKK.EEEEEE..RAVWA∆§∑wLMBPMJC`QJAWy.qJ@AVWPEVWSASEHOEHKJA.sLMWTAVWCQM@AQWLKIA.bKKPTVMJPWMJPLAWEJ@.pMIAWHMTWPLVKQCLKQVLEJ@W.IIIIII..gLKVQW∆§∑wKQHWaGLKy.SKKKKKK.MMMMMMMMM.bVAA@KIWFVAEPLEWSAAPGEVAWW.`AWAVP@VAEIWSAGKJBAWW..fVM@CA	aPLAVAEHsERAWy.pLANKQVJA]WAJ@]APSAFACMJ.eTEPLQJGLEVPA@@AATSMPLMJ.eLLLLLLLLLL.WKBPGLMIAy..RAVWAy.pLAWPEVWEHMCJKQVTEPLWAJPSMJA.e@EJGAKBBEPAMJPAVPSMJA@.mJPLA@AWAVPWAIFVEGASABMJ@KQVTHEGA..KQPVK	gAHAWPMEH`VMBPy.WWWLLLLKKKK.WKBPIEHAEJ@BAIEHASLMWTAVWhMFAVEPMKJ


MWKQVW


..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
