PMPHAaGLKAWKBPLAfE@fK]^.@AWGVMTPMKJqJ@AVGMP]HMCLPWWLE@KSW@EJGASMPLAGLKAWKBPEHAWQJPKH@
mJWTMVA@F]PLAWP]HAKBwl}ja
.TVKITPaJAVCAPMGLMT	LKTFAEPSMPL@AATFEWWCVMPP]W]JPLW@VMRMJCVL]PLIQVFEJWPVAAPRMFA@]JEIMGBHKSFKH@IEHARKGEHMJPAJWAEJ@VESIKK@.GKRAVeVPtVKITPgMP]WO]HMJAEPJMCLPJAKJHMCLPWVABHAGPMJCKJSAPWPVAAPWBQPQVMWPMGQVFEJRMFACVMPP]EJ@WP]HMWLRMFVEJPGKHKVGKJPVEWPWIK@AVJEJ@A@C].WB\GMP]PVEBBMG@MWPEJPWMVAJWFEWWPLQITWRMJ]HGVEGOHA.RKGEHWIEHARKGEHMJPAJWA@AHMRAV]VL]PLIMGRAVWAWVESEJ@TKSAVBQH.RKGEHWwPVQGPQVA@LMT	LKTPVEGOWPEVPWSMPLEWPVKJCMJPVKAJAVCAPMG@VKTWEJ@ETKSAVBQHKQPVKBAEPQVMJC@]JEIMGIEHARKGEHTAVBKVIEJGAW.OA]SKV@WLMT	LKTVETQVFEJAEWPGKEWPCVMPP]WPVAAPRMFAWJAKJHMPFEWWLAER]wl}jafE@fK]^IK@AVJFAEPVESAJAVC].GK@AjEIAaEWPKBa@AJ.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]wl}ja	fE@fK]^
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAVa.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGW..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
