PMPHAtQHWAKB`MWPEJP`VAEIWtQHWE^MKJA@MwKCJM`MWPEJPM.@AWGVMTPMKJmJESKVH@KBJAKJHMCLPWEJ@SLMWTAVW@VAEIWTQHWAPLVKQCLPLAJMCLP
mJWTMVA@F]PLAAWWAJGAKB@MWPEJPGKJJAGPMKJW
.TVKITPaJAVCAPMG@EJGARMFAW@AATLKQWAMJBHQAJGAWVL]PLIMGFAEPWRMFVEJPFEWWHMJAAQTLKVMGW]JPLWQTHMBPMJCEPIKWTLAVAIEHAEJ@BAIEHARKGEHWSMPLETHE]BQHEJ@SLMWTAV]PKJA
.GKRAVeVPtVKITPbQPQVMWPMGGMP]WGETAEPJMCLPJAKJHMCLPWVABHAGPMJCKJCHEWWFQMH@MJCWRMFVEJPEJ@@]JEIMGSMPLEWAJWAKBIKPMKJEJ@AJAVC]IK@AVJEJ@WHAAO@AWMCJLMCL	PAGLAHAIAJPW
.WB\GMP]PVEBBMGLQIAHAGPVKJMGFAATW@MWPEJPPLQJ@AVSMJ@SLKKWLLAEVPFAEPTQHWA.RKGEHW@QAPRKGEHTHE]BQHSLMWTAVWHE]AVA@LEVIKJMAWAHAGPVKJMGAGLKAW.RKGEHWwPVQGPQVA@@EJGAPVEGOSMPLEWPVKJCMJPVK@]JEIMGPVEJWMPMKJWEJ@EIAIKVEFHAKQPVKBAEPQVMJCIAHK@MGIEHAEJ@BAIEHARKGEHW.OA]SKV@W@EJGA@AATLKQWAAHAGPVKJMGLKQWAGHQFQTHMBPMJCBQPQVMWPMGJAKJRMFAWLMCLPAGLOVAJEVFJAIEJQAHEWHHEJM.GK@AjEIAtVM@AEJ@tVANQ@MGA.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]fjaIEJQAHeWHHEJM	oVAJEV
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAVt.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGW..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
